drop policy "device_insert" on "public"."devices";

drop policy "device_select" on "public"."devices";

revoke delete on table "public"."devices" from "anon";

revoke insert on table "public"."devices" from "anon";

revoke references on table "public"."devices" from "anon";

revoke select on table "public"."devices" from "anon";

revoke trigger on table "public"."devices" from "anon";

revoke truncate on table "public"."devices" from "anon";

revoke update on table "public"."devices" from "anon";

revoke delete on table "public"."devices" from "authenticated";

revoke insert on table "public"."devices" from "authenticated";

revoke references on table "public"."devices" from "authenticated";

revoke select on table "public"."devices" from "authenticated";

revoke trigger on table "public"."devices" from "authenticated";

revoke truncate on table "public"."devices" from "authenticated";

revoke update on table "public"."devices" from "authenticated";

revoke delete on table "public"."devices" from "service_role";

revoke insert on table "public"."devices" from "service_role";

revoke references on table "public"."devices" from "service_role";

revoke select on table "public"."devices" from "service_role";

revoke trigger on table "public"."devices" from "service_role";

revoke truncate on table "public"."devices" from "service_role";

revoke update on table "public"."devices" from "service_role";

alter table "public"."devices" drop constraint "devices_user_id_fkey";

alter table "public"."devices" drop constraint "devices_pkey";

drop index if exists "public"."devices_pkey";

drop table "public"."devices";

create table "public"."messages" (
    "id" bigint generated by default as identity not null,
    "created_at" timestamp with time zone not null default now(),
    "web_user_id" uuid not null,
    "phone_user_id" uuid not null,
    "firebase_id" text not null,
    "segment_count" smallint not null,
    "encoding_name" text not null
);


alter table "public"."messages" enable row level security;

alter table "public"."campaigns" alter column "name" set data type text using "name"::text;

alter table "public"."fcm_tokens" alter column "token" set data type text using "token"::text;

alter table "public"."pairing_secrets" alter column "secret" set data type text using "secret"::text;

CREATE UNIQUE INDEX messages_pkey ON public.messages USING btree (id);

alter table "public"."messages" add constraint "messages_pkey" PRIMARY KEY using index "messages_pkey";

alter table "public"."messages" add constraint "messages_phone_user_id_fkey" FOREIGN KEY (phone_user_id) REFERENCES auth.users(id) not valid;

alter table "public"."messages" validate constraint "messages_phone_user_id_fkey";

alter table "public"."messages" add constraint "messages_web_user_id_fkey" FOREIGN KEY (web_user_id) REFERENCES auth.users(id) not valid;

alter table "public"."messages" validate constraint "messages_web_user_id_fkey";

grant delete on table "public"."messages" to "anon";

grant insert on table "public"."messages" to "anon";

grant references on table "public"."messages" to "anon";

grant select on table "public"."messages" to "anon";

grant trigger on table "public"."messages" to "anon";

grant truncate on table "public"."messages" to "anon";

grant update on table "public"."messages" to "anon";

grant delete on table "public"."messages" to "authenticated";

grant insert on table "public"."messages" to "authenticated";

grant references on table "public"."messages" to "authenticated";

grant select on table "public"."messages" to "authenticated";

grant trigger on table "public"."messages" to "authenticated";

grant truncate on table "public"."messages" to "authenticated";

grant update on table "public"."messages" to "authenticated";

grant delete on table "public"."messages" to "service_role";

grant insert on table "public"."messages" to "service_role";

grant references on table "public"."messages" to "service_role";

grant select on table "public"."messages" to "service_role";

grant trigger on table "public"."messages" to "service_role";

grant truncate on table "public"."messages" to "service_role";

grant update on table "public"."messages" to "service_role";


